language: node_js
node_js:
  - 8 # 2019-12-01
  - lts/*
  - node

before_install:
  - if [[ `npm -v` = 3* ]]; then npm i -g npm@6; fi  

before_script:
  - npm run bootstrap
  - npm run build

script:
  - WITH_COVERAGE=1 npm test

after_success:
  -  npm run coverage.submit
